name: Deploy Abril Law Office App

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Set up SSH key
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_abril_law_office
        chmod 600 ~/.ssh/id_rsa_abril_law_office
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up SSH config
      run: |
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

    - name: Add SSH key and start agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa_abril_law_office

    - name: Deploy to Server
      run: |
        ssh root@91.108.104.53 '
          cd /var/www/Law-abril-portfolio &&
          git pull origin develop &&
          npm install &&
          npm run build &&
          pm2 restart Law-abril-portfolio ||
          pm2 start npm --name "Law-abril-portfolio" -- start --watch
        '
