# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.15.1]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Configure Git safe directory
      run: git config --global --add safe.directory ${{ secrets.WORKING_DIRECTORY }}
    - name: Pull latest code
      run: git pull origin develop
      working-directory: ${{ secrets.WORKING_DIRECTORY }}
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ secrets.WORKING_DIRECTORY }}
    - name: Build the project
      run: npm run build
      working-directory: ${{ secrets.WORKING_DIRECTORY }}
    - name: Restart PM2
      run: pm2 restart 0
      working-directory: ${{ secrets.WORKING_DIRECTORY }}
